version: '3.8'
services:
  backend:
    build: ../backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:///db/cloudsathi.db
  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    environment:
      - REACT_APP_API_URL=http://localhost:8000
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ../infra/db:/db
    command: ["sqlite3", "/db/cloudsathi.db"]
