version: '3.8'
services:
  backend:
    build: ../backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
      - ./db:/app/db
    env_file:
      - ../backend/.env
    environment:
      - DATABASE_URL=sqlite:///app/db/cloudsathi.db
    depends_on:
      - db
    command: >
      sh -c "mkdir -p /app/db &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
    stdin_open: true

  db:
    image: keinos/sqlite3:latest
    volumes:
      - ./db:/db
    command: >
      sh -c "mkdir -p /db &&
             touch /db/cloudsathi.db &&
             sqlite3 /db/cloudsathi.db '.databases'"
